create table atp_matches
(
    tourney_id         varchar(64) not null,
    tourney_name       varchar(200),
    surface            varchar(20),
    draw_size          smallint,
    tourney_level      varchar(10),
    tourney_date       date,
    match_num          smallint    not null,
    winner_id          integer,
    winner_seed        smallint,
    winner_entry       varchar(20),
    winner_name        varchar(200),
    winner_hand        varchar(10),
    winner_ht          smallint,
    winner_ioc         varchar(10),
    winner_age         double precision,
    loser_id           integer,
    loser_seed         smallint,
    loser_entry        varchar(20),
    loser_name         varchar(200),
    loser_hand         varchar(10),
    loser_ht           smallint,
    loser_ioc          varchar(10),
    loser_age          double precision,
    score              varchar(100),
    best_of            smallint,
    round              varchar(20),
    minutes            smallint,
    w_ace              smallint,
    w_df               smallint,
    w_svpt             smallint,
    w_1stin            smallint,
    w_1stwon           smallint,
    w_2ndwon           smallint,
    w_svgms            smallint,
    w_bpsaved          smallint,
    w_bpfaced          smallint,
    l_ace              smallint,
    l_df               smallint,
    l_svpt             smallint,
    l_1stin            smallint,
    l_1stwon           smallint,
    l_2ndwon           smallint,
    l_svgms            smallint,
    l_bpsaved          smallint,
    l_bpfaced          smallint,
    winner_rank        smallint,
    winner_rank_points smallint,
    loser_rank         smallint,
    loser_rank_points  smallint,
    constraint atp_matches_pkey
        primary key (tourney_id, match_num)
);